"""First migration

Revision ID: 77af61c17c9a
Revises: 
Create Date: 2022-03-16 01:29:52.369425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77af61c17c9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_hash'), 'posts', ['hash'], unique=True)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_hash'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
